"""
Django settings for data-aguas-rj project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
# import gzip
# import shutil
# from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# # Uncompress production database if present
# sqlite3db_gz = Path('{}/db.sqlite3.gz'.format(BASE_DIR))
# if sqlite3db_gz.is_file():
#     with open('{}/db.sqlite3'.format(BASE_DIR), 'wb') as f_out:
#         with gzip.open(sqlite3db_gz, 'rb', 9) as f_in:
#             shutil.copyfileobj(f_in, f_out)
#         os.remove(sqlite3db_gz)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', '*^2vc4$@xb@7(_-#e+z#_lhck%t0+2i+6i!0staw+00+&vow6@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'rest_framework',
    'reservatorios',
    'django_filters'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'site_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'site_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '{}/staticfiles/'.format(BASE_DIR)

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',)
}

"""
Constante com todos os reservatorios do estado do RJ.

Contém tuplas (id, nome_reservatorio)
"""

RESERVATORIOS_RJ = ((1, "14 DE JULHO", 19083),
                    (2, "A. VERMELHA", 19015),
                    (3, "AIMORES", 19111),
                    (4, "ANTA", 19140),
                    (5, "B. BONITA", 19040),
                    (6, "B.COQUEIROS", 19029),
                    (7, "BAGUARI", 19110),
                    (8, "BALBINA", 19141),
                    (9, "BARIRI", 19041),
                    (10, "BARRA GRANDE", 19067),
                    (11, "BATALHA", 19143),
                    (12, "BILLINGS", 19036),
                    (13, "BOA ESPERANÇA", 19127),
                    (14, "C. DOURADA", 19026),
                    (15, "C.BRANCO-1", 19020),
                    (16, "C.BRANCO-2", 19021),
                    (17, "CACONDE", 19011),
                    (18, "CACU", 19028),
                    (19, "CAMARGOS", 19001),
                    (20, "CAMPOS NOVOS", 19068),
                    (21, "CANA BRAVA", 19129),
                    (22, "CANDONGA", 19109),
                    (23, "CANOAS I", 19054),
                    (24, "CANOAS II", 19053),
                    (25, "CAPIVARA", 19055),
                    (26, "CASTRO ALVES", 19081),
                    (27, "CHAVANTES", 19050),
                    (28, "COARACY NUNES", 19144),
                    (29, "CORUMBA", 19024),
                    (30, "CORUMBA-3", 19023),
                    (31, "CORUMBA-4", 19022),
                    (32, "CURUA-UNA", 19139),
                    (33, "D. FRANCISCA", 19080),
                    (34, "DARDANELOS", 19145),
                    (35, "E. DA CUNHA", 19012),
                    (36, "EDGARD SOUZA", 19039),
                    (37, "EMBORCAÇÃO", 19017),
                    (38, "ERNESTINA", 19076),
                    (39, "ESPORA", 19033),
                    (40, "ESTREITO", 19133),
                    (41, "FERREIRA GOMES", 19146),
                    (42, "FONTES", 19102),
                    (43, "FOZ CHAPECO", 19073),
                    (44, "FOZ R.CLARO", 19030),
                    (45, "FUNDÃO", 19062),
                    (46, "FUNIL", 19093),
                    (47, "FUNIL-MG", 19003),
                    (48, "FURNAS", 19004),
                    (49, "G. B. MUNHOZ", 19059),
                    (50, "G. P. SOUZA", 19084),
                    (51, "GARIBALDI", 19147),
                    (52, "GUAPORE", 19136),
                    (53, "GUARAPIRANGA", 19037),
                    (54, "GUILM. AMORIM", 19105),
                    (55, "HENRY BORDEN", 19035),
                    (56, "I. SOLTEIRA", 19034),
                    (57, "IBITINGA", 19042),
                    (58, "IGARAPAVA", 19008),
                    (59, "ILHA POMBOS", 19097),
                    (60, "IRAPE", 19115),
                    (61, "ITÁ", 19070),
                    (62, "ITAIPU", 19058),
                    (63, "ITAPEBI", 19116),
                    (64, "ITAUBA", 19079),
                    (65, "ITIQUIRA I", 19087),
                    (66, "ITUMBIARA", 19025),
                    (67, "ITUTINGA", 19002),
                    (68, "JACUI", 19078),
                    (69, "JAGUARA", 19007),
                    (70, "JAGUARI", 19092),
                    (71, "JAURU", 19089),
                    (72, "JIRAU", 19148),
                    (73, "JORDÃO", 19063),
                    (74, "JUPIA", 19046),
                    (75, "JURUMIRIM", 19048),
                    (76, "L. C. BARRETO", 19006),
                    (77, "LAJEADO", 19132),
                    (78, "LAJES", 19099),
                    (79, "LIMOEIRO", 19013),
                    (80, "LUIZ GONZAGA", 19122),
                    (81, "M. MORAES", 19005),
                    (82, "MACHADINHO", 19069),
                    (83, "MANSO", 19086),
                    (84, "MARIMBONDO", 19014),
                    (85, "MASCARENHAS", 19112),
                    (86, "MAUÁ", 19142),
                    (87, "MIRANDA", 19019),
                    (88, "MONJOLINHO", 19072),
                    (89, "MONTE CLARO", 19082),
                    (90, "MOXOTO", 19123),
                    (91, "N. AVANHANDAVA", 19044),
                    (92, "NILO PEÇANHA", 19103),
                    (93, "NOVA PONTE", 19018),
                    (94, "OURINHOS", 19051),
                    (95, "P. AFONSO 4", 19125),
                    (96, "P. COLOMBIA", 19010),
                    (97, "PARAIBUNA", 19090),
                    (98, "PASSO FUNDO", 19071),
                    (99, "PASSO REAL", 19077),
                    (100, "PASSO SÃO JOÃO", 19149),
                    (101, "PEDRA DO CAVALO", 19117),
                    (102, "PEIXE ANGICAL", 19131),
                    (103, "PEREIRA PASSOS", 19104),
                    (104, "PICADA", 19095),
                    (105, "PIRAJU", 19049),
                    (106, "PONTE DE PEDRA", 19088),
                    (107, "PONTE NOVA", 19038),
                    (108, "PORTO ESTRELA", 19108),
                    (109, "PORTO PRIMAVERA", 19047),
                    (110, "PROMISSÃO", 19043),
                    (111, "QUEBRA QUEIXO", 19074),
                    (112, "QUEIMADO", 19120),
                    (113, "RETIRO BAIXO", 19118),
                    (114, "RONDON II", 19138),
                    (115, "ROSAL", 19113),
                    (116, "ROSANA", 19057),
                    (117, "S.DO FACÃO", 19016),
                    (118, "S.R.VERDINHO", 19032),
                    (119, "SA CARVALHO", 19106),
                    (120, "SALTO", 19031),
                    (121, "SALTO CAXIAS", 19066),
                    (122, "SALTO GRANDE CM", 19107),
                    (123, "SALTO GRANDE CS", 19052),
                    (124, "SALTO OSORIO", 19065),
                    (125, "SALTO PILAO", 19085),
                    (126, "SALTO SANTIAGO", 19064),
                    (127, "SAMUEL", 19137),
                    (128, "SANTA BRANCA", 19091),
                    (129, "SANTA CECILIA", 19094),
                    (130, "SANTA CLARA-PR", 19061),
                    (131, "SANTANA", 19100),
                    (132, "SANTO ANTONIO", 19135),
                    (133, "SANTO ANTÔNIO DO JARI", 19151),
                    (134, "SAO JOSE", 19075),
                    (135, "SAO SALVADOR", 19130),
                    (136, "SÃO SIMÃO", 19027),
                    (137, "SEGREDO", 19060),
                    (138, "SERRA DA MESA", 19128),
                    (139, "SIMPLÍCIO", 19150),
                    (140, "SOBRADINHO", 19121),
                    (141, "SOBRAGI", 19096),
                    (142, "STA.CLARA-MG", 19114),
                    (143, "TAQUARUÇU", 19056),
                    (144, "TOCOS", 19098),
                    (145, "TRÊS IRMÃOS", 19045),
                    (146, "TRÊS MARIAS", 19119),
                    (147, "TUCURUI", 19134),
                    (148, "VIGARIO", 19101),
                    (149, "VOLTA GRANDE", 19009),
                    (150, "XINGO", 19126))
