# Generated by Django 2.0.2 on 2018-02-10 06:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cota', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Cota (m)')),
                ('afluencia', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Afluência (m³/s)')),
                ('defluencia', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Defluência (m³/s)')),
                ('vazao_vertida', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Vazão Vertida (m³/s)')),
                ('vazao_turbinada', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Vazão Turbinada (m³/s)')),
                ('vazao_natural', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Vazão Natural (m³/s)')),
                ('volume_util', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=7, null=True, verbose_name='Volume Útil (%)')),
                ('vazao_incremental', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Vazão Incremental (m³/s)')),
                ('data_da_medicao', models.DateField(verbose_name='Data da medição')),
            ],
            options={
                'verbose_name': 'medição',
                'verbose_name_plural': 'medições',
            },
        ),
        migrations.CreateModel(
            name='Reservatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('estado', models.CharField(default='RJ', max_length=2)),
                ('codigo_ana', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'repositório',
                'verbose_name_plural': 'repositórios',
            },
        ),
        migrations.AddIndex(
            model_name='reservatorio',
            index=models.Index(fields=['codigo_ana'], name='reservatori_codigo__70b73d_idx'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='reservatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservatorios.Reservatorio'),
        ),
        migrations.AddIndex(
            model_name='medicao',
            index=models.Index(fields=['data_da_medicao'], name='reservatori_data_da_5eadbf_idx'),
        ),
    ]
