# Generated by Django 2.0.2 on 2018-02-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicao',
            index=models.Index(fields=['volume_util'], name='reservatori_volume__64d600_idx'),
        ),
    ]
